###Creating a new blog with userId 6590875f6e939d9f6558c260
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "We need to stay focus, we can not forget the basic way",
    "author": "Kurapika Stain",
    "url": "http://hunterxhunter.com",
    "likes": 23,
    "userId" : "6590875f6e939d9f6558c260"
}

###Creating a new blog with userId 659087576e939d9f6558c25c
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "We never stop to coding, today is the last day of the year 2023",
    "author": "Jorge Navarro",
    "url": "http://jorgnavarro.com",
    "likes": 31,
    "userId" : "659087576e939d9f6558c25c"
}

###Login simulation functional user 1
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Programmer",
    "password" : "fullstack10"
}

###Login simulation functional user 1
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "root",
    "password" : "khease"
}

###Login simulation functional user 2
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Hunter",
    "password" : "khease"
}





###Creating a new note with user 1 simulation login
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlByb2dyYW1tZXIiLCJpZCI6IjY1OTA4NzU3NmU5MzlkOWY2NTU4YzI1YyIsImlhdCI6MTcwNDIyNTAxMywiZXhwIjoxNzA0MjI4NjEzfQ.PSZdH_C4EhEANWL4TWd5LZ7KVIwCjYZEwX7hTwlzpfc

{
    "title": "Testing middlewares final part",
    "author": "Jorge Navarro",
    "url": "http://programmer.com",
    "likes": 5
}

###Creating a new note with user 2 simulation login
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikh1bnRlciIsImlkIjoiNjU5MDg3NWY2ZTkzOWQ5ZjY1NThjMjYwIiwiaWF0IjoxNzA0MjI0NzcxLCJleHAiOjE3MDQyMjgzNzF9.4rVKLFGASzZACyUPVGwRt-M9RJCkKEdQRaAzdAwzdDU

{
    "title": "Blog for test middlewares final test",
    "author": "Kurapika Kurta",
    "url": "http://hunterxhunter.com",
    "likes": 70
}

###Delete a blog with jwt, Hunter user
DELETE http://localhost:3003/api/blogs/659375d1f23f91d738e21407
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikh1bnRlciIsImlkIjoiNjU5MDg3NWY2ZTkzOWQ5ZjY1NThjMjYwIiwiaWF0IjoxNzA0MjI0NzcxLCJleHAiOjE3MDQyMjgzNzF9.4rVKLFGASzZACyUPVGwRt-M9RJCkKEdQRaAzdAwzdDU

###Delete a blog with jwt, Programmer user
DELETE http://localhost:3003/api/blogs/6594692caa13eccaffca99f1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlByb2dyYW1tZXIiLCJpZCI6IjY1OTA4NzU3NmU5MzlkOWY2NTU4YzI1YyIsImlhdCI6MTcwNDIyNTAxMywiZXhwIjoxNzA0MjI4NjEzfQ.PSZdH_C4EhEANWL4TWd5LZ7KVIwCjYZEwX7hTwlzpfc



